// Code generated by "stringer -type=AircraftStatus"; DO NOT EDIT.

package types

import "strconv"

const _AircraftStatus_name = "StandingMovingAirborn"

var _AircraftStatus_index = [...]uint8{0, 8, 14, 21}

func (i AircraftStatus) String() string {
	if i < 0 || i >= AircraftStatus(len(_AircraftStatus_index)-1) {
		return "AircraftStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AircraftStatus_name[_AircraftStatus_index[i]:_AircraftStatus_index[i+1]]
}
